### ISSUE TITLE
Deploy complex umbrella app (this one!)

### ISSUE THREAD

**Issue by katbow** [healthlocker/oxleas-adhd#108]
This issue is not yet broken down as we are still going through #106 & #107. After completing these, we should have a better idea of how this will break down. For now with seeing how long it takes for simpler apps, we've added this as an initial estimate of the deploy.

**Comment by katbow** [comment]
Now that we've completed #107, we'll be breaking this down as the next step.

**Comment by markwilliamfirth** [comment]
- [x] README for how to get oxleas ADHD up and running (T1h)

- [x] README for how to deploy Oxleas ADHD (T4h)

- [x] Review of project and deployment code with QA (T1.5h)

- [ ] Deploy the project (T1d)

[Time estimated steps of deployment to be written up here for transparency]

**Comment by reddog** [comment]
@markwilliamfirth Thanks for your deployment notes. Thanks @RobStallion for your work on #110 and getting the app installed.

Just wanted to check, is this issue the right place for the deployment plan?

As discussed, the plan should include setting up SSL, see #94.

It should also include setting up AWS SES as that has been the chosen outgoing email mechanism, see #32 and #33.

Any manual tasks like #1 should also be on the list. Are there any other similar issues?

**Comment by reddog** [comment]
@RobStallion Thanks for your notes on https://github.com/healthlocker/healthlocker/issues/999  Is this the list you were referring to of specific things to check in Oxleas post-deployment?  Messaging was an issue previously - does that need adding?

**Comment by reddog** [comment]
@markwilliamfirth Sorry for a couple further notes:

Does the deployment plan include `nginx` setup as listed on the Healthlocker deployment at https://github.com/healthlocker/healthlocker/issues/841 ?

Is Travis CI/CD also on the plan as per https://github.com/healthlocker/healthlocker/pull/959 ?

**Comment by katbow** [comment]
@reddog there's still a day left from the original 4 day estimate. @RobStallion & I paired from Wed afternoon to end of day Friday, then Rob worked on his own yesterday for deployment which is 3 pairing days. 

Those are parts of the deployment plan, however they were not added in yet as there were some questions regarding ssl that @katyedwards was chasing up. At yesterday's stand up, Katy mentioned that if there is no reply, then to just go ahead with those issues so it's done.

The related issues for this part are #1, #32, #33 (which altogether should be t25 as it is just changing environment variables), #49 & #94. It's likely we will need to include nginx setup as part of those. 

Travis CI/CD is not included in this.

**Comment by reddog** [comment]
@katbow Thanks for your comments.

Sorry, I was working from the passed on comment that deployment was *virtually finished*.  I'm not 100% sure which issue relates to the deployment plan (see my comment above), and hence have added queries here - very happy to put them against another issue if more appropriate.

Things like AWS SES setup & configuration, nginx and Travis weren't previously included anywhere, and since I'm not 100% sure where the deployment plan is, I couldn't verify for myself if they are being covered or not.

Is there any downside to Travis not being included?  Work has been completed to get it (almost?) running for SLaM's Healthlocker.

**Comment by katbow** [comment]
> Sorry, I was working from the passed on comment that deployment was virtually finished

yes, that's correct. The app is deployed & can be accessed at the url I put on slack(http://51.140.117.78/). 

As I said [here](https://github.com/healthlocker/oxleas-adhd/issues/108#issuecomment-324022702), those items were not included in the deployment plan because there were blockers for it. Additionally, the deployment was not **dependent** on those issues being completed; rather that the deployment needed to be finished before those issues could be started. They are need to dos though, for having a 'prettier' url to visit, and enabling https. 

Issues related to the actual deployment are #50, #106, #107, this one, & #110.

As for the travis CI, almost is the key word there. The time constraints for this project mean we do not have time to finish that off ourselves, and it is really more of a nice to have than necessity. The app is deployable without it, it just needs to be done manually with a few commands from [this section](https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md#build-the-release).

**Comment by reddog** [comment]
@markwilliamfirth Can the remaining tasks for full project deployment please be listed and addressed well before the end of the week to accommodate any potential issues, eg SSL, nigjnx, AWS SES, etc

**Comment by markwilliamfirth** [comment]
@reddog please see here (https://github.com/healthlocker/oxleas-adhd/issues/126) and update the issue according to your needs!

**Comment by reddog** [comment]
@markwilliamfirth Thanks very much for opening #126 - I'll take a look.

I probably mis-worded my request - there is not issue with the remaining *project* deployment tasks split out, eg nginx.  I want to try to ensure they don't slip down any gaps, plus time estimate if required and assign to people.  Can <-- this issue be created please?

**Comment by markwilliamfirth** [comment]
@reddog I think it might be clearer for everyone if you open an issue with a description (including requirements) of what you'd like and we can action it as I'm not 100% what your requirements are in this context

**Comment by reddog** [comment]
@markwilliamfirth I'm not sure that I am the best person to confirm *all* of the steps required for the *full project* deployment, so my opening the issue would be a partial list at best.  I have done my best to list a number of items above - I don't know if it's exhaustive or not.

The items (that I've listed) above don't show time estimates or persons assigned.

**Comment by markwilliamfirth** [comment]
@reddog I think it might be best if you (or the product owner) creates a new issue for this and we can then augment it once we've read and understood your needs - seems like we're both a little unsure of the requirements here!

**Comment by markwilliamfirth** [comment]
@reddog we normally follow this format for issue creation:

As a CTO of Mindwave Ventures
I would like...
So that...

The requirements are:

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by reddog** [comment]
@markwilliamfirth Sorry for not explaining myself very well.  It would be good to speak as I'm not doing well and getting my thoughts down well in writing.  Please let me know when we can speak.

**Comment by markwilliamfirth** [comment]
@reddog unfortunately my time is very limited tomorrow morning with other commitments (I'm also booked off in the afternoon) and I'm not able to assign time to additional phone calls in the morning

@katyedwards would you be able to help us here with regards to us getting this clarified in writing?

With regards to the mention about SSL, there is already an SSL issue here: #94 

It would be great to get the requirements clarified in writing early tomorrow if possible so we're all on the same page.

**Comment by reddog** [comment]
@markwilliamfirth Thanks for that.  Sorry I wasn't able to speak today since you're unavailable tomorrow.

Would Rob or Katherine be available to speak to instead?

**Comment by markwilliamfirth** [comment]
@reddog Rob and Katherine will be working on development and additional phone calls would cut into this time - I would suggest we try and write down requirements if possible as this is our standard process and the most time-efficient to ensure we can deliver the project on time. We've already gone over on the assigned time for standup calls and so I wouldn't introduce more time for calls as this might risk essential time that is required for development and bug fixes etc

**Comment by reddog** [comment]
@markwilliamfirth I have reopened #50 and referred to comments above. I think that captures everything. Please let me know if there are any remaining uncertainties.

**Comment by katyedwards** [comment]
@reddog as you commented last, I'll ask you... can this one be closed now?

**Comment by reddog** [comment]
This has been deployed now.
