### ISSUE TITLE
Deploy application to Azure 

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#110]
- [x] Create readme with full list of instructions for how to deploy umbrella application to the the Azure environment. - 4h

- [x] Update application to allow for deployment to take place. -1h (will be based on what was learned in #107) Steps to complete... 
  - [x] add `edeliver` & `distillery`
  - [x] move `package.json` and `brunch-config.js` into project route
  - [x] update 'package.json and `brunch-config.js` with instructions found in README.
  - [x] update `apps/healthlocker/config/prod.exs` with instructions found in README.

- [x] Configure edeliver -30m (will be based on what was learned in #107)
- [x] Build with edeliver - 4h (buffer added as this has been where most problems came up with #106 & #107)

**Comment by RobStallion** [comment]
relates to #50 #107

**Comment by RobStallion** [comment]
to test deployment of full umbrella app, the repo has been forked [here] (https://github.com/RobStallion/oxleas-adhd). 
This will allow us to make changes and test the deployment configurations faster as we will not have to wait for things to merged into master. Once the correct set up has been found it can be replicated in this repo.

**Comment by RobStallion** [comment]
following steps found [here]() and the comments made in #106 & #107 have been able to deploy the oxleas-adhd umbrella application. However we are currently getting the following error...

```
connection not available because of disconnection
```

![image](https://user-images.githubusercontent.com/15571853/29517377-bb5c7ffa-866c-11e7-8766-e4a947f36e92.png)

**Comment by RobStallion** [comment]
this seems to be an error with `apps/healthlocker/config/prod.exs` file so going to start looking here first.

**Comment by RobStallion** [comment]
static pages (ones with no reliance on the database) seem to be working...

![image](https://user-images.githubusercontent.com/15571853/29517653-f41decec-866d-11e7-805a-94cbf5a4bd14.png)

Currently looking into the file mentioned in the comment above for possible caused for why the database connection would not be working

**Comment by RobStallion** [comment]
Could possibly be an issue with the `secret_key_base`...
```
cookie store expects conn.secret_key_base to be set
```

**Comment by RobStallion** [comment]
issue was with the `env vars` on the VM. Has now been resolved 

![image](https://user-images.githubusercontent.com/15571853/29522632-bf1ac146-8681-11e7-8071-50384d727118.png)

**Comment by RobStallion** [comment]
This app is now deployed 😭
