### ISSUE TITLE
Seeing microseconds in tracker over 0 entry

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#153]
+ [x] fix to remove microseconds as per Healthlocker https://github.com/healthlocker/healthlocker/issues/830

**Comment by MollieCourtenay** [comment]
+ [ ] microseconds is displaying for average.
+ [ ] microseconds for today input 0.0 hours sleep.


This has been fixed in healthlocker...


<img width="600" alt="screen shot 2017-09-11 at 11 40 21" src="https://user-images.githubusercontent.com/25012688/30270863-0f741c22-96e6-11e7-801f-509b7c4d973a.png">

**Comment by iteles** [comment]
Apologies @MollieCourtenay, this had not yet been deployed! Ready to test again now.

**Comment by MollieCourtenay** [comment]
👍
