### ISSUE TITLE
Within Admin system: add new Teacher/ Other Professional

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#178]
As an Oxleas team member I want to be able to add a new Teacher/ Other Professional to the system (as a 4th user type) so that I can connect them to a SU.

# Acceptance Criteria

+ [x] add a new button to the Admin dashboard '2. Add Teacher'
+ [x] To add a new Teacher/ OP, I will have to enter their First Name, Last Name, School / Organisation, Job Role / Title, Email and Password.
+ [x] display Teachers in a list at the bottom of the Admin dashboard.

# Tasks
- [x] Create form
- [x]  Link up to correct permissions

close to clinician #21

**Comment by MollieCourtenay** [comment]
<img width="367" alt="screen shot 2017-09-11 at 15 02 16" src="https://user-images.githubusercontent.com/25012688/30278444-4621797e-9702-11e7-9ace-ac3d4d6cc101.png">
<img width="369" alt="screen shot 2017-09-11 at 15 02 03" src="https://user-images.githubusercontent.com/25012688/30278445-465bbe86-9702-11e7-8623-59bbc5b3e0aa.png">

**Comment by SimonLab** [comment]
I'm creating a migration to add the "org" field to the users (to represent to scholl for teachers). However I've got  the folloeing error:
![image](https://user-images.githubusercontent.com/6057298/34995859-aad66d12-facf-11e7-8c85-de5d42155125.png)

I don't think I should update the dependencies inside the umbrella app, the main app should already have them up to date I think. I'm going to investigate a bit more otherwise I will create manually the migration file

**Comment by SimonLab** [comment]
I managed the create a migration with ```mix ecto.gen.migration``` but had to clean some code linked to Appsignal. @katbow kindly (thanks again!) created a PR that should fix the issues linked to Appsignal configuration, see #257

**Comment by katyedwards** [comment]
LGTM!
