### ISSUE TITLE
Service user can choose what tracking / goals and strategies to share with Teachers.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#182]
As a service user, I can choose whether or not to share my tracking / goals and strategies with Teachers that I am connected to.

**Please estimate all three options (add more if you see them):**
+ [ ] editing sharing choice per post (at an individual tracking / dairy post/ individual goal/ coping strategy level) 
+ [ ] one-off but editable sharing choice per feature (I choose to share goals, but not coping strategies with my teacher, but tomorrow I can choose to share coping strategies and not goals)
+ [ ] I choose to share all (same as clinician) or nothing (like carer) with my teachers. 

NOTE: all goals / strategies / tracking is ALWAYS shared with the clinician.

**Comment by katbow** [comment]
Bit confused with this one. I understand the point that there should be a choice for what they want to share, but I'm confused on who they have an option to share with & the differences in some of these options.

Right now carers don't see any tracking/goals & strategies from the service user. Would this be updated to be more like clinician view of a service user, except with sharing preferences?

I'm a bit confused as well with what some of these mean. For example, I'm not sure of the difference between 

> I choose to share all (same as clinician) or nothing (like carer) with my teachers. For Teachers/OPs Only

and

> I choose to share all (same as clinician) or nothing (like carer) with my teachers. For Teachers and Carers

I guess that goes for each set with the only difference being *For Teachers/OPs Only* or *For Teachers and Carers*. Does this mean who is choosing this, or who is viewing it, or some combination of both..?

**Comment by katyedwards** [comment]
Sorry, I think I was trying to make that clearer but failed!

Have  re-written above... is that better?! @katbow

**Comment by katbow** [comment]
For each of these, I think the extra time with doing this for a carer would come from changing how the care team section loads/displays.  Adds an extra 1.5 days to each one for changing the carer display to show these sections, as they are not present at all. 

> editing sharing choice per post (at an individual tracking / diary post/ individual goal/ coping strategy level)

**T3d**
T1d = setting up new fields in relevant tables & adding to each form. 
T1d = Display in tracking for each section. Need to add clause to for loop for each item on if it should be displayed or not
T1d = changing set up for tracking. 

This would involve a new field which can be updated each time an item is created/updated. This would mean adding minimum 1 field (or 2 if also shared with carers) for each of the tables to share. Each form would need checkboxes added for `share with teacher?` and same for `share with carer`. This would be set to true or false depending on checkbox ticked/unticked when adding or editing. Displaying would need to be done on a per item basis rather than a whole section.

Potential problem?? How this works for sleep & problem tracking - since it's graphed data, we would need to add more logic to how to get the data for teachers (or carers) depending if that item for that day is shareable or not. Possible workaround could be a default for all users on whether the graph itself is shared, but the extra details are only displayed if selected to do so.

> one-off but editable sharing choice per feature (I choose to share goals, but not coping strategies with my teacher, but tomorrow I can choose to share coping strategies and not goals)

**T2d** *Note* should be able to save ~T4h if the tracking overview is done as a whole rather than per section. E.g. either show all of diary, sleep, and problem tracking, or none of it.
T1d = create new table & add to each section for saving preference
T1d = display each section based on preferences. This is quick for goals & coping strategies as they are better separated out, but longer for tracking if each section can be chosen individually.

Would need additional `sharing` table, with fields for each section they can choose to share. Include list in this table of who it is shared with. 

> I choose to share all (as I do with clinicians) or nothing (as I currently do with carers) with my teachers.

**T4h**
Database update for user to be true/false for sharing (could have 2 fields, one for sharing with carer, one for sharing with teacher). Display checkbox somewhere (?? not sure where) for if they want to share data with their teacher (or a second checkbox if carer is included). Display in each section a message along the lines of `Information not shared` if it's set to false.

**Comment by katbow** [comment]
@katyedwards Sorry if that's a bit blabby - was throwing out some ideas/options.

**Comment by katyedwards** [comment]
Lovely thanks, that's really helpful @katbow

**Comment by MollieCourtenay** [comment]
not to share default.

**Comment by MollieCourtenay** [comment]
change mind.
change mind to no more sharing - remove all.
change mind, to yes - only share from then on.

**Comment by iteles** [comment]
Our assumption here is that in terms of UI, the teacher view will be the same as the clinician view (with adequate permissions) so no new pages will need to be created.

Our second assumption is that carers are not included in this issue.

**Comment by katyedwards** [comment]
@iteles yep - both assumptions correct
