### ISSUE TITLE
Within Admin system: add new user

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#21]
_Note: Edited to add issue numbers only_

The roles are:
+ Clinician #57 
+ Service user #58 
+  Carer #59 

+ [x] If I am adding a new clinician, I will have to enter their first name, last name, email address, password, job role.
_______
+ [x] If I am adding a new service user, I will have to enter their first name, last name, DOB, email address, password, then save.
+ [x] I will then be asked to assign clinicians to the service user, I can select multiple clinicians, then save.
________
+ [x] If I am adding a new carer, I will have to enter the carer's first name, last name, email address, password, relationship to the service user.
+ [x] I will then be asked to assign a service user to the carer, I will have to enter the service users' first name, last name, DOB. Then click locate.
+ [x] IF, there is a service user account with those details, I am asked to confirm and connect.
+ [x] IF, there is NOT a service user account with those details, I am prompted to check those details and try again or go back to see if there is an account for the person I am looking for, and if not create one first.
________

NOTE TO TEAM:

password could be set as password. 
Users are prompted to change it the first time they log in.

**Comment by MollieCourtenay** [comment]
![admin wireframes_add users](https://user-images.githubusercontent.com/25012688/27825972-4e74c4e4-60a9-11e7-9a03-fc8a97b2daa1.png)

**Comment by iteles** [comment]
Password creation by super admins was discussed at length. 
Although dwyl advises against this due to the security vulnerabilities that it creates, it was determined by our PO @katyedwards that given that Oxleas will be hand-holding users through their first exposure to the app, this would be the fastest way (given budget constraints) to resolve the issue in the short term.

**Comment by katyedwards** [comment]
Clinician and SU are good.

Blocked by #59

**Comment by katyedwards** [comment]
#59 now closed so this can be too!
