### ISSUE TITLE
Add Send Button on Messaging

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#227]
Add a send button to the messaging.
Under the text box, aligned to the right

**Comment by katyedwards** [comment]
Time estimate based on https://github.com/healthlocker/healthlocker/issues/904 but hopefully might be less as the only requirement from the client is to add a send button

**Comment by iteles** [comment]
## Tasks
+ [ ] Add send button as above
+ [ ] Hook up send button to actually 'send'
+ [ ] Disable sending on 'enter' key press

**Comment by katyedwards** [comment]
For the send button asset... it should look like the various save buttons but with the text 'Send'
e.g.
![screenshot 2018-01-15 16 21 05](https://user-images.githubusercontent.com/24604903/34952056-47061144-fa10-11e7-9740-52968ddcffe3.png)

Do you need an asset provided for this or can you use the existing bits?

**Comment by katyedwards** [comment]
This isn't top priority, so will depend how everything else goes....

So sorry!  I hadn't noticed in the steps that we were disabling send on 'enter' key.

Is it a hassle to enable this again so users have the option to either hit 'enter' or use the new send button?

**Comment by katyedwards** [comment]
Perfect thank you!
