### ISSUE TITLE
Change "Problem Tracker" to "Progress Tracker"

### ISSUE THREAD

**Issue by ghost** [healthlocker/oxleas-adhd#328]
SU/Carer View:
- [ ] On toolkit button
- [ ] New Problem Page - https://focus.headscapegreenwich.co.uk/symptom/new
- [ ] Track Problem Page
- [ ] Tracking Overview - key above graph (If no data has been entered)

Clinician View:
- [ ] Tracking Overview - key above graph (If no data has been entered)
