### ISSUE TITLE
Within Admin system: add new Service User

### ISSUE THREAD

**Issue by iteles** [healthlocker/oxleas-adhd#58]
As there is no ePJS system to check user details against, these will be manually entered by the Oxleas team in an Admin area #2.

As an Oxleas team member I want to be able to add a new service user to the system so that I can ensure those who we work with have access to the application for their wellbeing.

## Acceptance Criteria
(taken from #21)

+ [x] If I am adding a new service user, I will have to enter their first name, last name, DOB, email address, password, then save.
+ [x] I will then be asked to assign clinicians to the service user, I can select multiple clinicians, then save.

### Tasks
  + [x] Create form including pulling in staff section
  + [x] Link up permissions + clinicians

**Comment by katbow** [comment]
When connecting clinicians, there's no need for the rest of the form to be editable (name, email, etc). This fits with how staff and carers are added. The details for the service user can still be visible on this page so the super admin knows who they are adding/editing clinicians for. However, the best option we can see is...

The flow would appear the same:
* The user is created
* The data for the user is displayed (not editable)
* There's a section underneath which is the form to add clinicians for that user
* Super admin clicks save & the clinicians are added #62 
* Clinicians section can be edited later (but not the service user section) #24

**Comment by MollieCourtenay** [comment]
+ [ ] the first name and last name fields need to be on the same line.

**Comment by katyedwards** [comment]
Yep, all good!
