### ISSUE TITLE
Within Admin system: add new Carer - Flash Message

### ISSUE THREAD

**Issue by iteles** [healthlocker/oxleas-adhd#59]
As there is no ePJS system to check user details against, these will be manually entered by the Oxleas team in an Admin area #2.

As an Oxleas team member I want to be able to add a carer to the system so that I can ensure they are able to partake in the care of the young person for whom they are a carer.

## Acceptance Criteria
(taken from #21)

+ [x] If I am adding a new carer, I will have to enter the carer's first name, last name, email address, password, relationship to the service user.
+ [x] I will then be asked to assign a service user to the carer, I will have to enter the service users' first name, last name, DOB. Then click locate.
+ [x] IF, there is a service user account with those details, I am asked to confirm and connect.
+ [x] IF, there is NOT a service user account with those details, I am prompted to check those details and try again or go back to see if there is an account for the person I am looking for, and if not create one first.

### Tasks
  + [x] Create form 
  + [x] Create correct permissions
  + [x] Check to see if SU exists and link users as well as creating error path if not

**Comment by MollieCourtenay** [comment]
Note to ensure the buttons are the right way around. Save and locate.???

**Comment by katyedwards** [comment]
@MollieCourtenay All works fine, but one nit-picky bit...

_IF, there is NOT a service user account with those details, I am prompted to check those details and try again or go back to see if there is an account for the person I am looking for, and if not create one first._

Right now, it just says SU cannot be found, it doesn't actually prompt to check the details and try again...

![screenshot 2017-08-23 12 25 11](https://user-images.githubusercontent.com/24604903/29613498-2e9ca0ac-87fe-11e7-905c-d6a3d9ca456e.png)

I'll leave you to close this if you're happy and maybe raise another issue to enhance in the future, or leave this open to be edited.

**Comment by MollieCourtenay** [comment]
The flash message should say: 

No user found. Check the details you entered and try again. Or go back to see if there is an account for the person you are looking for, and if not create one first.

In order to answer the  original ACS.

**Comment by katbow** [comment]
@Cleop This is another small one as well post-demo. 
- [ ] When details entered are incorrect, change flash message to say:

> No user found. Check the details you entered and try again. Or go back to see if there is an account for the person you are looking for, and if not create one first.

**Comment by katyedwards** [comment]
Thanks - flash message now correct and save/locate buttons are right way round
