### ISSUE TITLE
Umbrella integration

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#90]
- [x] Change functionality for connecting & adding clinicians/carer/service users to rooms #99 

- [x] Put oxleas in the umbrella apps

- [x] Put all routes in the 'Healthlocker' router #100

- [x] check routes run as expected #100
- [x] Update controllers that need changing #103
    - [x] `CaseloadController`
    - [x] `web/controllers/caseload`
    - [x] 'web/controllers/care_team`
    - [x] `LoginController`

**Comment by markwilliamfirth** [comment]
@RobStallion to split out controllers issue

**Comment by katbow** [comment]
All related issues complete
